# Generated by Django 4.0.1 on 2022-10-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField(max_length=1500, unique=True)),
                ('answer_option_1', models.CharField(max_length=100)),
                ('answer_option_2', models.CharField(max_length=100)),
                ('answer_option_3', models.CharField(max_length=100)),
                ('answer_option_4', models.CharField(max_length=100)),
                ('correct_option', models.CharField(choices=[(1, 'Option 1'), (2, 'Option 2'), (3, 'Option 3'), (4, 'Option 4')], default=1, max_length=10)),
            ],
        ),
    ]
