# Generated by Django 4.0.1 on 2022-10-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelquestion',
            name='correct_option',
            field=models.CharField(choices=[(1, 'Option 1'), (2, 'Option 2'), (3, 'Option 3'), (4, 'Option 4')], default='Option 1', max_length=10),
        ),
    ]
