# Generated by Django 4.0.1 on 2022-10-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_modelquestion_correct_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelquestion',
            name='correct_option',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Option 1'), (2, 'Option 2'), (3, 'Option 3'), (4, 'Option 4')]),
        ),
    ]
