# Generated by Django 4.0.1 on 2022-10-30 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_modelquestion_correct_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelquestion',
            old_name='question_text',
            new_name='question',
        ),
    ]
